# This workout builds an angular application
# For more information see https://github.com/marketplace/actions/angular-deploy-gh-pages-actions

name: Build and Deploy
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          base_href: time-organiser
          deploy_branch: gh-pages

permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.
